import test from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import fs from "node:fs/promises";

test("Suki shell references SukiUI and Maa.Framework as the replacement desktop stack", async () => {
  const csproj = await fs.readFile("apps/rhodes-suki/RhodesSuki.csproj", "utf8");
  const packageJson = await fs.readFile("package.json", "utf8");

  assert.match(csproj, /PackageReference Include="SukiUI" Version="7\.0\.1"/);
  assert.match(csproj, /PackageReference Include="Maa\.Framework" Version="5\.8\.0"/);
  assert.match(csproj, /resource\\base\\pipeline\\rhodes\.json/);
  assert.match(csproj, /resource\\base\\pipeline\\rhodes-generated\.json/);
  assert.match(csproj, /interface\.json/);
  assert.match(csproj, /assets\\recognition\\templates\\run\\\*\.png/);
  assert.match(csproj, /assets\\operators\\\*\*\\\*\.png/);
  assert.match(csproj, /assets\\relics\\\*\*\\\*\.png/);
  assert.match(csproj, /data\\campaigns\.json/);
  assert.match(csproj, /data\\operators\.json/);
  assert.match(csproj, /data\\relics\.json/);
  assert.match(csproj, /data\\current-state\.json/);
  assert.match(csproj, /data\\selectable-effects\.json/);
  assert.match(csproj, /data\\recognition\\maa-tasks\.json/);
  assert.match(csproj, /data\\recognition\\scan-profiles\.json/);
  assert.match(packageJson, /"maa:resource:generate": "node tools\/generate-maa-resource\.mjs"/);
  assert.match(packageJson, /"maa:resource:check": "node tools\/generate-maa-resource\.mjs --check"/);
  assert.match(packageJson, /"suki:test": "dotnet run --project tests\/rhodes-suki\/RhodesSuki\.ServiceTests\.csproj"/);
  assert.match(packageJson, /suki:publish:portable.*--self-contained true/);
});

test("Suki service tests cover MAA Resource detail conversion behavior", async () => {
  const testProject = await fs.readFile("tests/rhodes-suki/RhodesSuki.ServiceTests.csproj", "utf8");
  const program = await fs.readFile("tests/rhodes-suki/Program.cs", "utf8");

  assert.match(testProject, /ProjectReference Include="..\\..\\apps\\rhodes-suki\\RhodesSuki\.csproj"/);
  assert.match(program, /RhodesMaaResultPreview\.FromTaskResults/);
  assert.match(program, /best_result/);
  assert.match(program, /filtered_results/);
  assert.match(program, /TemplateMatch/);
  assert.match(program, /HitFallback/);
  assert.match(program, /RhodesAdbPresetCatalog\.DefaultPresets/);
  assert.match(program, /RhodesAdbDeviceProbe\.ParseDevices/);
  assert.match(program, /RhodesSukiSettingsStore\.Save/);
  assert.match(program, /google-play-games-dev/);
});

test("Suki shell keeps MAA session and probe code in thin RHODES-owned services", async () => {
  const session = await fs.readFile("apps/rhodes-suki/Services/RhodesMaaSession.cs", "utf8");
  const optionalRuntimeProbe = await fs.readFile("apps/rhodes-suki/Services/RhodesOptionalRuntimeProbe.cs", "utf8");
  const hypervisorProbe = await fs.readFile("apps/rhodes-suki/Services/RhodesHypervisorProbe.cs", "utf8");
  const runtimeProbe = await fs.readFile("apps/rhodes-suki/Services/MaaFrameworkRuntimeProbe.cs", "utf8");
  const probe = await fs.readFile("apps/rhodes-suki/Services/RhodesRecognitionProbe.cs", "utf8");
  const catalog = await fs.readFile("apps/rhodes-suki/Services/RhodesMaaResourceCatalog.cs", "utf8");
  const adbPresets = await fs.readFile("apps/rhodes-suki/Services/RhodesAdbPresetCatalog.cs", "utf8");
  const adbDeviceProbe = await fs.readFile("apps/rhodes-suki/Services/RhodesAdbDeviceProbe.cs", "utf8");
  const settingsStore = await fs.readFile("apps/rhodes-suki/Services/RhodesSukiSettingsStore.cs", "utf8");
  const diagnostics = await fs.readFile("apps/rhodes-suki/Services/RhodesMaaTaskDiagnostics.cs", "utf8");
  const ocrDetailRows = await fs.readFile("apps/rhodes-suki/Services/RhodesMaaOcrDetailRows.cs", "utf8");
  const roiDetailRows = await fs.readFile("apps/rhodes-suki/Services/RhodesMaaRoiDetailRows.cs", "utf8");
  const roiEditDraftLog = await fs.readFile("apps/rhodes-suki/Services/RhodesMaaRoiEditDraftLog.cs", "utf8");
  const roiAdjustmentSessionLog = await fs.readFile("apps/rhodes-suki/Services/RhodesMaaRoiAdjustmentSessionLog.cs", "utf8");
  const roiDraftSourceUpdater = await fs.readFile("apps/rhodes-suki/Services/RhodesMaaRoiDraftSourceUpdater.cs", "utf8");
  const roiDraftBatchSourceUpdater = await fs.readFile("apps/rhodes-suki/Services/RhodesMaaRoiDraftBatchSourceUpdater.cs", "utf8");
  const generatedResourceBuilder = await fs.readFile("apps/rhodes-suki/Services/RhodesMaaGeneratedResourceBuilder.cs", "utf8");
  const roiPreviewProjector = await fs.readFile("apps/rhodes-suki/Services/RhodesMaaRoiPreviewProjector.cs", "utf8");
  const roiSelectionMatcher = await fs.readFile("apps/rhodes-suki/Services/RhodesMaaRoiSelectionMatcher.cs", "utf8");
  const resultPreview = await fs.readFile("apps/rhodes-suki/Services/RhodesMaaResultPreview.cs", "utf8");
  const runCatalog = await fs.readFile("apps/rhodes-suki/Services/RhodesRunCatalog.cs", "utf8");
  const bitmapPathConverter = await fs.readFile("apps/rhodes-suki/Services/RhodesBitmapPathConverter.cs", "utf8");
  const choiceFilter = await fs.readFile("apps/rhodes-suki/Services/RhodesChoiceFilter.cs", "utf8");
  const choiceRows = await fs.readFile("apps/rhodes-suki/Services/RhodesChoiceRows.cs", "utf8");
  const operatorTaxonomy = await fs.readFile("apps/rhodes-suki/Services/RhodesOperatorTaxonomy.cs", "utf8");
  const runStateStore = await fs.readFile("apps/rhodes-suki/Services/RhodesRunStateStore.cs", "utf8");
  const candidateApplier = await fs.readFile("apps/rhodes-suki/Services/RhodesRecognitionCandidateApplier.cs", "utf8");
  const candidateApiClient = await fs.readFile("apps/rhodes-suki/Services/RhodesMaaCandidateApiClient.cs", "utf8");
  const scanApiClient = await fs.readFile("apps/rhodes-suki/Services/RhodesRecognitionScanApiClient.cs", "utf8");
  const scanHistory = await fs.readFile("apps/rhodes-suki/Services/RhodesRecognitionScanHistory.cs", "utf8");
  const debugPaths = await fs.readFile("apps/rhodes-suki/Services/RhodesSukiDebugPaths.cs", "utf8");
  const stateApiClient = await fs.readFile("apps/rhodes-suki/Services/RhodesStateApiClient.cs", "utf8");
  const models = await fs.readFile("apps/rhodes-suki/Models/MaaSessionModels.cs", "utf8");
  const runModels = await fs.readFile("apps/rhodes-suki/Models/RunCatalogModels.cs", "utf8");
  const viewModel = await fs.readFile("apps/rhodes-suki/ViewModels/MainWindowViewModel.cs", "utf8");
  const mainWindowCodeBehind = await fs.readFile("apps/rhodes-suki/Views/MainWindow.axaml.cs", "utf8");
  const mainWindowAxaml = await fs.readFile("apps/rhodes-suki/Views/MainWindow.axaml", "utf8");
  const resource = await fs.readFile("apps/rhodes-suki/resource/base/pipeline/rhodes.json", "utf8");
  const generatedResource = await fs.readFile("apps/rhodes-suki/resource/base/pipeline/rhodes-generated.json", "utf8");
  const projectInterface = await fs.readFile("apps/rhodes-suki/interface.json", "utf8");

  assert.match(session, /new MaaAdbController/);
  assert.match(session, /new MaaTasker/);
  assert.match(session, /GetCachedImage/);
  assert.match(session, /AppendTask/);
  assert.match(session, /GetRecognitionDetail/);
  assert.match(session, /RecognitionDetailJson/);
  assert.match(probe, /AppendRecognition/);
  assert.match(probe, /TemplateMatch/);
  assert.match(probe, /RecognitionDetailJson/);
  assert.match(catalog, /rhodes-generated\.json/);
  assert.match(catalog, /JsonDocument\.Parse/);
  assert.match(catalog, /GeneratedTasks/);
  assert.match(catalog, /ProfileGroups/);
  assert.match(catalog, /profileIds/);
  assert.match(adbPresets, /google-play-games-dev/);
  assert.match(adbPresets, /127\.0\.0\.1:6520/);
  assert.match(adbPresets, /127\.0\.0\.1:16384/);
  assert.match(adbDeviceProbe, /devices/);
  assert.match(adbDeviceProbe, /ParseDevices/);
  assert.match(settingsStore, /suki-settings\.json/);
  assert.match(settingsStore, /RhodesSukiSettings/);
  assert.match(diagnostics, /RhodesMaaTaskDiagnostics/);
  assert.match(diagnostics, /RhodesMaaResultPreview\.FromTaskResults/);
  assert.match(resultPreview, /FromTaskResults/);
  assert.match(resultPreview, /best_result/);
  assert.match(resultPreview, /filtered_results/);
  assert.match(resultPreview, /MaaCandidatePreview/);
  assert.match(runCatalog, /campaigns\.json/);
  assert.match(runCatalog, /operators\.json/);
  assert.match(runCatalog, /relics\.json/);
  assert.match(runCatalog, /current-state\.json/);
  assert.match(runCatalog, /selectable-effects\.json/);
  assert.match(runCatalog, /ResolveStatePath/);
  assert.match(runCatalog, /IsProjectRootStatePath/);
  assert.match(runCatalog, /ResolveLocalPath/);
  assert.match(runCatalog, /SukiRunStateSnapshot/);
  assert.match(bitmapPathConverter, /IValueConverter/);
  assert.match(bitmapPathConverter, /new Bitmap\(path\)/);
  assert.match(choiceFilter, /ShowSelectedFirst/);
  assert.match(choiceFilter, /HideExcluded/);
  assert.match(choiceFilter, /SelectedOnly/);
  assert.match(choiceFilter, /RequiresFullRefreshAfterSelectionMutation/);
  assert.match(choiceFilter, /RequiresFullRefreshAfterExclusionMutation/);
  assert.match(choiceFilter, /OperatorClass/);
  assert.match(choiceFilter, /OperatorBranch/);
  assert.match(choiceFilter, /Category/);
  assert.match(choiceFilter, /Rarity/);
  assert.match(choiceRows, /Math\.Clamp\(columns, 1, 4\)/);
  assert.match(choiceRows, /new SukiChoiceRow/);
  assert.match(operatorTaxonomy, /SortClasses/);
  assert.match(operatorTaxonomy, /SortBranches/);
  assert.match(operatorTaxonomy, /"先鋒"/);
  assert.match(operatorTaxonomy, /"執行者"/);
  assert.match(runStateStore, /SaveChoicesAsync/);
  assert.match(runStateStore, /SaveRunContextAsync/);
  assert.match(runStateStore, /SaveCandidatesAsync/);
  assert.match(runStateStore, /ReplaceStateJsonAsync/);
  assert.match(runStateStore, /SemaphoreSlim/);
  assert.match(runStateStore, /operatorExcludedIds/);
  assert.match(runStateStore, /operatorGridColumns/);
  assert.match(candidateApplier, /ApplyRunStatus/);
  assert.match(candidateApplier, /ApplyStringSetCandidate/);
  assert.match(candidateApplier, /commandLevel/);
  assert.match(candidateApplier, /squadId/);
  assert.match(candidateApplier, /idea/);
  assert.match(candidateApplier, /operator/);
  assert.match(candidateApplier, /relic/);
  assert.match(models, /MaaTaskDetailSnapshot/);
  assert.match(models, /MaaResourceProfilePreview/);
  assert.match(models, /EditKindLabel/);
  assert.match(models, /ProjectedRoiJson/);
  assert.match(models, /TopLeftHandleX/);
  assert.match(models, /TopLeftHandleY/);
  assert.match(models, /LeftHandleX/);
  assert.match(models, /TopHandleX/);
  assert.match(models, /RightHandleX/);
  assert.match(models, /BottomHandleX/);
  assert.match(models, /ResizeHandleX/);
  assert.match(models, /ResizeHandleY/);
  assert.match(models, /IsResourceRoiCandidate/);
  assert.match(models, /MaaRoiEditDraft/);
  assert.match(models, /MaaRoiDraftApplyResult/);
  assert.match(models, /MaaRoiBatchApplyResult/);
  assert.match(models, /MaaRoiBatchDraftPreview/);
  assert.match(models, /MaaRoiAdjustmentSessionDraft/);
  assert.match(models, /MaaRoiAdjustmentSessionPayload/);
  assert.match(models, /MaaRoiAdjustmentSessionItem/);
  assert.match(models, /MaaRoiRescanComparisonRow/);
  assert.match(models, /SafeComparisonRows/);
  assert.match(models, /ComparisonCount/);
  assert.match(models, /SafeComparisonBeforeLogPath/);
  assert.match(models, /SafeComparisonAfterLogPath/);
  assert.match(models, /ValueDiff/);
  assert.match(models, /IsIncluded/);
  assert.match(models, /StateLabel/);
  assert.match(models, /StateDetail/);
  assert.match(models, /TargetSummary/);
  assert.match(models, /DiffSummary/);
  assert.match(models, /BackupSummary/);
  assert.match(models, /MaaResourceGenerationResult/);
  assert.match(models, /FromPreview/);
  assert.match(models, /SukiOptionalRuntimeStatus/);
  assert.match(models, /MaaCandidatePreview/);
  assert.match(models, /SukiCandidateApplySummary/);
  assert.match(models, /ProfileIds/);
  assert.match(models, /SourceSummary/);
  assert.match(models, /RecognitionDetailJson/);
  assert.match(runModels, /SukiCampaignPreview/);
  assert.match(runModels, /SukiSpecialFieldState/);
  assert.match(runModels, /SukiChoiceItem/);
  assert.match(runModels, /SukiChoiceRow/);
  assert.match(runModels, /ImagePath/);
  assert.match(runModels, /SelectionButtonLabel/);
  assert.match(runModels, /ExclusionButtonLabel/);
  assert.match(viewModel, /ConnectCommand/);
  assert.match(viewModel, /CaptureCommand/);
  assert.match(viewModel, /Bitmap/);
  assert.match(viewModel, /LastCaptureImage/);
  assert.match(viewModel, /AdbPresets/);
  assert.match(viewModel, /AdbDevices/);
  assert.match(viewModel, /ApplyAdbPresetCommand/);
  assert.match(viewModel, /RefreshAdbDevicesCommand/);
  assert.match(viewModel, /ApplyAdbDeviceCommand/);
  assert.match(viewModel, /RefreshOptionalRuntimesCommand/);
  assert.match(viewModel, /RhodesOptionalRuntimeProbe\.ProbeAsync/);
  assert.match(viewModel, /_maaFrameworkStatus\.State/);
  assert.match(viewModel, /_maaFrameworkStatus\.Detail/);
  assert.match(viewModel, /_rhodesApiStatus\.State/);
  assert.match(viewModel, /RHODES API/);
  assert.match(viewModel, /SaveSettingsCommand/);
  assert.match(viewModel, /LoadSettings/);
  assert.match(viewModel, /ResourceTaskDiagnostics/);
  assert.match(viewModel, /MaaOcrStatusState/);
  assert.match(viewModel, /Resource化済み/);
  assert.doesNotMatch(viewModel, /"MAA-OCR",\s*"移行対象"/);
  assert.match(viewModel, /RunAllProbesCommand/);
  assert.match(viewModel, /RunSelectedProfileRecognitionCommand/);
  assert.match(viewModel, /RunSelectedProfileRecognitionAndApplyCommand/);
  assert.match(viewModel, /OpenRecognitionProfileCommand/);
  assert.match(viewModel, /RunAllResourceTasksCommand/);
  assert.match(viewModel, /ExportResourceTaskResultsCommand/);
  assert.match(viewModel, /SelectedResourceProfile/);
  assert.match(viewModel, /RefreshResourceTasks/);
  assert.match(viewModel, /ConvertResourceTaskResultsCommand/);
  assert.match(viewModel, /ApplyCandidateResultsCommand/);
  assert.match(viewModel, /LastCandidateApplySummary/);
  assert.match(viewModel, /LastResourceTaskResultsPath/);
  assert.match(viewModel, /RefreshChoicesFromRunState/);
  assert.match(viewModel, /RhodesMaaCandidateApiClient\.ConvertAsync/);
  assert.match(viewModel, /RhodesMaaLocalCandidateConverter\.FromTaskResults/);
  assert.match(candidateApiClient, /api\/recognition\/maa-resource/);
  assert.match(candidateApiClient, /ExtractCandidatePreviews/);
  assert.match(scanApiClient, /api\/recognition\/scan/);
  assert.match(scanApiClient, /ExtractResult/);
  assert.match(scanApiClient, /RhodesMaaCandidateApiClient\.ExtractCandidatePreviews/);
  assert.match(stateApiClient, /api\/state/);
  assert.match(viewModel, /SyncRunStateFromApiCommand/);
  assert.match(viewModel, /SyncRunStateFromApiCoreAsync/);
  assert.match(viewModel, /RhodesStateApiClient\.FetchAsync/);
  assert.match(viewModel, /RhodesRunStateStore\.ReplaceStateJsonAsync/);
  assert.match(viewModel, /CandidateApiProfileId/);
  assert.match(viewModel, /RunSelectedProfileAdbScanCommand/);
  assert.match(viewModel, /RhodesRecognitionScanApiClient\.RunAsync/);
  assert.doesNotMatch(viewModel, /SelectedResourceProfile\?\.Id == "all" \? "runStatusFull"/);
  assert.match(viewModel, /RhodesMaaResultPreview\.FromTaskResults/);
  assert.match(viewModel, /CandidateResults/);
  assert.match(viewModel, /RunResourceTaskCommand/);
  assert.match(viewModel, /RecognitionScanHistory/);
  assert.match(viewModel, /RecognitionScanLogRows/);
  assert.match(viewModel, /RefreshRecognitionScanHistoryCommand/);
  assert.match(viewModel, /LoadRecognitionScanHistoryCommand/);
  assert.match(viewModel, /RhodesRecognitionScanHistory\.LoadRecent/);
  assert.match(viewModel, /RhodesRecognitionScanHistory\.LoadPayload/);
  assert.match(viewModel, /TryLoadCapturePreviewFromPath/);
  assert.match(viewModel, /RhodesSukiDebugPaths\.RecognitionScansDirectory/);
  assert.match(viewModel, /RhodesMaaRecognitionEvidenceLog\.SaveAsync/);
  assert.match(scanHistory, /recognition-\*\.json/);
  assert.match(scanHistory, /LoadPayload/);
  assert.match(scanHistory, /ExtractTaskResults/);
  assert.match(scanHistory, /ExtractLogRows/);
  assert.match(models, /FirstImagePath/);
  assert.match(models, /HasImagePath/);
  assert.match(scanHistory, /ResourceTaskCount/);
  assert.match(scanHistory, /CandidateCount/);
  assert.match(ocrDetailRows, /filtered_results/);
  assert.match(ocrDetailRows, /best_result/);
  assert.match(ocrDetailRows, /all_results/);
  assert.match(viewModel, /OcrDetailRows/);
  assert.match(roiDetailRows, /TryPointBoxRect/);
  assert.match(roiDetailRows, /roi/);
  assert.match(roiDetailRows, /rect/);
  assert.match(viewModel, /RoiDetailRows/);
  assert.match(viewModel, /RoiPreviewRows/);
  assert.match(viewModel, /SelectedRoiPreviewRow/);
  assert.match(viewModel, /SelectedRoiPreviewRows/);
  assert.match(viewModel, /SelectedRoiEditDraft/);
  assert.match(viewModel, /ExportSelectedRoiDraftCommand/);
  assert.match(viewModel, /PreviewSelectedRoiDraftApplyCommand/);
  assert.match(viewModel, /ApplySelectedRoiDraftCommand/);
  assert.match(viewModel, /PreviewVisibleRoiDraftsApplyCommand/);
  assert.match(viewModel, /ApplyVisibleRoiDraftsCommand/);
  assert.match(viewModel, /IncludeAllRoiBatchDraftsCommand/);
  assert.match(viewModel, /ExcludeAllRoiBatchDraftsCommand/);
  assert.match(viewModel, /SetAllRoiBatchDraftsIncludedAsync/);
  assert.match(viewModel, /UpdateRoiBatchDraftStates/);
  assert.match(viewModel, /VisibleResourceRoiDrafts/);
  assert.match(viewModel, /RegenerateMaaResourceCommand/);
  assert.match(viewModel, /MaaResourceGenerationResult/);
  assert.match(viewModel, /RoiDraftApplyResult/);
  assert.match(viewModel, /RoiBatchApplyResult/);
  assert.match(viewModel, /RoiBatchDrafts/);
  assert.match(viewModel, /RhodesMaaRoiEditDraftLog\.SaveAsync/);
  assert.match(viewModel, /ExportRoiAdjustmentSessionCommand/);
  assert.match(viewModel, /LastRoiSessionPath/);
  assert.match(viewModel, /RoiAdjustmentSessions/);
  assert.match(viewModel, /RoiSessionRestoreNotice/);
  assert.match(viewModel, /RoiRescanComparisonRows/);
  assert.match(viewModel, /RoiRescanComparisonSummary/);
  assert.match(viewModel, /RoiRescanComparisonEvidenceSummary/);
  assert.match(viewModel, /SetRoiRescanComparisonEvidence/);
  assert.match(viewModel, /beforeEvidencePath/);
  assert.match(viewModel, /OpenRoiRescanEvidenceCommand/);
  assert.match(viewModel, /OpenRoiRescanEvidenceAsync/);
  assert.match(viewModel, /比較証跡を開きました/);
  assert.match(viewModel, /comparisonSummary: RoiRescanComparisonSummary/);
  assert.match(viewModel, /comparisonRows: RoiRescanComparisonRows/);
  assert.match(viewModel, /comparisonBeforeLogPath: _lastRoiRescanBeforePath/);
  assert.match(viewModel, /comparisonAfterLogPath: _lastRoiRescanAfterPath/);
  assert.match(viewModel, /payload\.SafeComparisonRows/);
  assert.match(viewModel, /payload\.SafeComparisonSummary/);
  assert.match(viewModel, /payload\.SafeComparisonBeforeLogPath/);
  assert.match(viewModel, /payload\.SafeComparisonAfterLogPath/);
  assert.match(viewModel, /RunRoiRescanComparisonCommand/);
  assert.match(viewModel, /RunRoiRescanComparisonAsync/);
  assert.match(viewModel, /CompareRoiRescanCandidates/);
  assert.match(viewModel, /SnapshotCandidatesForComparison/);
  assert.match(viewModel, /BuildRoiRescanComparisonSummary/);
  assert.match(viewModel, /ClearRoiRescanComparison/);
  assert.match(viewModel, /RefreshRoiAdjustmentSessionsCommand/);
  assert.match(viewModel, /LoadRoiAdjustmentSessionCommand/);
  assert.match(viewModel, /LoadRoiAdjustmentSessionAsync/);
  assert.match(viewModel, /LoadRecognitionPayload/);
  assert.match(viewModel, /ClearRecognitionPayload/);
  assert.match(viewModel, /SelectRoiPreviewCommand/);
  assert.match(viewModel, /SelectRoiPreviewAsync/);
  assert.match(viewModel, /RoiSnapStep/);
  assert.match(viewModel, /RoiSnapStepLabel/);
  assert.match(viewModel, /SetRoiSnapStepCommand/);
  assert.match(viewModel, /SetRoiSnapStepAsync/);
  assert.match(viewModel, /ResetSelectedRoiDraftCommand/);
  assert.match(viewModel, /ResetSelectedRoiDraftAsync/);
  assert.match(viewModel, /ROIを元に戻しました/);
  assert.match(viewModel, /SnapDelta/);
  assert.match(viewModel, /BeginRoiDrag/);
  assert.match(viewModel, /UpdateRoiDrag/);
  assert.match(viewModel, /EndRoiDrag/);
  assert.match(viewModel, /BeginRoiResize/);
  assert.match(viewModel, /UpdateRoiResize/);
  assert.match(viewModel, /EndRoiResize/);
  assert.match(viewModel, /CancelRoiInteraction/);
  assert.match(viewModel, /RestoreSelectedRoi/);
  assert.match(viewModel, /ROIドラッグをキャンセル/);
  assert.match(viewModel, /_roiResizeMode/);
  assert.match(viewModel, /topLeft/);
  assert.match(viewModel, /right/);
  assert.match(viewModel, /bottom/);
  assert.match(viewModel, /Math\.Clamp/);
  assert.match(viewModel, /AdjustSelectedRoiDraftCommand/);
  assert.match(viewModel, /AdjustSelectedRoiDraftAsync/);
  assert.match(viewModel, /UpdateSelectedRoiOverlay/);
  assert.match(viewModel, /UpdateRoiBatchDraftForSelected/);
  assert.match(viewModel, /TryParseDraftRoi/);
  assert.match(viewModel, /AdjustRoi\(roi, operation, RoiSnapStep\)/);
  assert.match(viewModel, /RhodesMaaRoiAdjustmentSessionLog\.SaveAsync/);
  assert.match(viewModel, /RhodesMaaRoiAdjustmentSessionLog\.LoadRecent/);
  assert.match(viewModel, /RhodesMaaRoiAdjustmentSessionLog\.Load/);
  assert.match(viewModel, /RhodesRecognitionScanHistory\.LoadPayload\(payload\.ScanLogPath\)/);
  assert.match(viewModel, /同じ画面を再スキャン/);
  assert.match(mainWindowAxaml, /調整後再スキャン比較/);
  assert.match(mainWindowAxaml, /RoiRescanComparisonRows/);
  assert.match(mainWindowAxaml, /RoiRescanComparisonEvidenceSummary/);
  assert.match(mainWindowAxaml, /RunRoiRescanComparisonCommand/);
  assert.match(mainWindowAxaml, /OpenRoiRescanEvidenceCommand/);
  assert.match(mainWindowAxaml, /CommandParameter="before"/);
  assert.match(mainWindowAxaml, /CommandParameter="after"/);
  assert.match(roiAdjustmentSessionLog, /maa-roi-adjustment-session/);
  assert.match(roiAdjustmentSessionLog, /SaveAsync/);
  assert.match(roiAdjustmentSessionLog, /Load/);
  assert.match(roiAdjustmentSessionLog, /LoadRecent/);
  assert.match(roiAdjustmentSessionLog, /roi-session-\*\.json/);
  assert.match(roiAdjustmentSessionLog, /MaaRoiAdjustmentSessionDraft\.FromPreview/);
  assert.match(roiAdjustmentSessionLog, /comparisonRows/);
  assert.match(roiAdjustmentSessionLog, /comparisonBeforeLogPath/);
  assert.match(roiAdjustmentSessionLog, /comparisonAfterLogPath/);
  assert.match(viewModel, /ResolveRoiDraftSourcePath/);
  assert.match(viewModel, /RhodesMaaRoiDraftSourceUpdater\.ApplyToSourceJson/);
  assert.match(viewModel, /RhodesMaaRoiDraftSourceUpdater\.ApplyToSourceFileAsync/);
  assert.match(viewModel, /RhodesMaaGeneratedResourceBuilder\.RegenerateFileAsync/);
  assert.match(viewModel, /ReloadResourceCatalog/);
  assert.match(viewModel, /_allResourceTasks = RhodesMaaResourceCatalog\.DefaultTasks\(\)/);
  assert.match(viewModel, /ReloadMaaResourceSessionIfReadyAsync/);
  assert.match(viewModel, /_session\.InitializeAdbAsync\(BuildSessionOptions\(\)\)/);
  assert.match(viewModel, /Resource再読込済み/);
  assert.match(viewModel, /未接続のため次回接続時に反映/);
  assert.match(mainWindowCodeBehind, /RoiOverlayPointerPressed/);
  assert.match(mainWindowCodeBehind, /RoiOverlayPointerMoved/);
  assert.match(mainWindowCodeBehind, /RoiOverlayPointerReleased/);
  assert.match(mainWindowCodeBehind, /viewModel\.BeginRoiDrag/);
  assert.match(mainWindowCodeBehind, /viewModel\.UpdateRoiDrag/);
  assert.match(mainWindowCodeBehind, /viewModel\.EndRoiDrag/);
  assert.match(mainWindowCodeBehind, /CancelRoiInteractionOnEscape/);
  assert.match(mainWindowCodeBehind, /Key\.Escape/);
  assert.match(mainWindowCodeBehind, /viewModel\.CancelRoiInteraction/);
  assert.match(mainWindowCodeBehind, /_roiActivePointer\?\.Capture\(null\)/);
  assert.match(mainWindowCodeBehind, /RoiResizePointerPressed/);
  assert.match(mainWindowCodeBehind, /RoiResizePointerMoved/);
  assert.match(mainWindowCodeBehind, /RoiResizePointerReleased/);
  assert.match(mainWindowCodeBehind, /viewModel\.BeginRoiResize\(row, RoiPointerX\(e\), RoiPointerY\(e\), control\.Tag as string\)/);
  assert.match(mainWindowCodeBehind, /viewModel\.UpdateRoiResize/);
  assert.match(mainWindowCodeBehind, /viewModel\.EndRoiResize/);
  assert.match(roiDraftSourceUpdater, /ApplyToScanProfilesJson/);
  assert.match(roiDraftSourceUpdater, /ApplyToSourceJson/);
  assert.match(roiDraftSourceUpdater, /templateOcrRegions/);
  assert.match(roiDraftSourceUpdater, /searchRoi/);
  assert.match(roiDraftBatchSourceUpdater, /ApplyToSourceJsons/);
  assert.match(roiDraftBatchSourceUpdater, /ApplyToSourceFilesAsync/);
  assert.match(roiDraftBatchSourceUpdater, /MaaRoiBatchApplyResult/);
  assert.match(roiDraftBatchSourceUpdater, /updatedMaaTasksJson/);
  assert.match(roiDraftBatchSourceUpdater, /updatedScanProfilesJson/);
  assert.match(viewModel, /RefreshSelectedRoiPreviewRows/);
  assert.match(viewModel, /SelectedOcrDetailRow/);
  assert.match(viewModel, /SelectedResourceTaskResult/);
  assert.match(viewModel, /SelectedRecognitionScanLogRow/);
  assert.match(viewModel, /SelectRoiForOcrDetail/);
  assert.match(viewModel, /SelectRoiForTaskResult/);
  assert.match(viewModel, /SelectRoiForLogRow/);
  assert.match(viewModel, /RhodesMaaRoiSelectionMatcher\.MatchForOcrDetail/);
  assert.match(viewModel, /RhodesMaaRoiSelectionMatcher\.MatchForTaskResult/);
  assert.match(viewModel, /RhodesMaaRoiSelectionMatcher\.MatchForLogRow/);
  assert.match(roiSelectionMatcher, /MatchForTaskResult/);
  assert.match(roiSelectionMatcher, /MatchForLogRow/);
  assert.match(roiSelectionMatcher, /StartsWith/);
  assert.match(viewModel, /CapturePixelSizeLabel/);
  assert.match(viewModel, /RoiProjectionLabel/);
  assert.match(viewModel, /PixelSize/);
  assert.match(viewModel, /RhodesMaaRoiPreviewProjector\.Project/);
  assert.match(roiPreviewProjector, /imageWidth/);
  assert.match(roiPreviewProjector, /baseResolution\.Width/);
  assert.match(viewModel, /ShowRoiOverlay/);
  assert.match(debugPaths, /Recognition Scans/);
  assert.match(debugPaths, /ROI Drafts/);
  assert.match(debugPaths, /ROI Sessions/);
  assert.match(roiEditDraftLog, /maa-roi-edit-draft/);
  assert.match(roiEditDraftLog, /SaveAsync/);
  assert.match(roiDraftSourceUpdater, /data\/recognition\/maa-tasks\.json/);
  assert.match(roiDraftSourceUpdater, /RhodesOcrRegion/);
  assert.match(roiDraftSourceUpdater, /ocrRegions/);
  assert.match(roiDraftSourceUpdater, /ApplyToMaaTasksFileAsync/);
  assert.match(roiDraftSourceUpdater, /BackupPath/);
  assert.match(generatedResourceBuilder, /maa-tasks\.json/);
  assert.match(generatedResourceBuilder, /scan-profiles\.json/);
  assert.match(generatedResourceBuilder, /TemplateMatch/);
  assert.match(generatedResourceBuilder, /RhodesTemplate/);
  assert.match(generatedResourceBuilder, /RegenerateFileAsync/);
  assert.match(viewModel, /Campaigns/);
  assert.match(viewModel, /SelectedCampaign/);
  assert.match(viewModel, /構想/);
  assert.doesNotMatch(viewModel, /想念/);
  assert.match(viewModel, /FilteredOperators/);
  assert.match(viewModel, /FilteredRelics/);
  assert.match(viewModel, /FilteredOperatorRows/);
  assert.match(viewModel, /FilteredRelicRows/);
  assert.match(viewModel, /ToggleChoiceSelectedCommand/);
  assert.match(viewModel, /ToggleChoiceExcludedCommand/);
  assert.match(viewModel, /PaneColumnOptions/);
  assert.match(viewModel, /OperatorPaneColumns/);
  assert.match(viewModel, /RelicPaneColumns/);
  assert.match(viewModel, /ClampPaneColumns/);
  assert.match(viewModel, /RefreshChoiceAfterSelectionMutation/);
  assert.match(viewModel, /RefreshChoiceAfterExclusionMutation/);
  assert.match(viewModel, /PersistChoiceStateInBackground\(\);/);
  assert.match(viewModel, /RefreshOperatorSummaries/);
  assert.match(viewModel, /RefreshRelicSummaries/);
  assert.match(viewModel, /RefreshOperatorRows/);
  assert.match(viewModel, /RefreshRelicRows/);
  assert.match(viewModel, /RhodesOperatorTaxonomy\.SortClasses/);
  assert.match(viewModel, /RhodesOperatorTaxonomy\.SortBranches/);
  assert.match(viewModel, /RhodesRunStateStore\.SaveChoicesAsync/);
  assert.match(viewModel, /RhodesRunStateStore\.SaveCandidatesAsync/);
  assert.match(viewModel, /SetCurrentCampaignCommand/);
  assert.match(viewModel, /SequenceEqual\(items\)/);
  assert.match(mainWindowCodeBehind, /CloseOpenComboBoxesOnOutsidePress/);
  assert.match(mainWindowCodeBehind, /IsDropDownOpen = false/);
  assert.match(resource, /RhodesRunStatusTopBarOcr/);
  assert.match(resource, /RhodesOperatorCodenameFlag/);
  assert.match(resource, /OperatorCardCodeNameFlag\.png/);
  assert.match(generatedResource, /RhodesOcrRegion_run_hope_current/);
  assert.match(generatedResource, /RhodesTemplate_runStatusFull_run_ingot/);
  assert.match(generatedResource, /scan-profiles\.templateOcrRegions/);
  assert.match(projectInterface, /"interface_version": 2/);
  assert.match(projectInterface, /"entry": "RhodesOperatorNameOcr"/);
  assert.match(resource, /RhodesProbe/);
  assert.match(optionalRuntimeProbe, /api\/ocr\/glm\/status/);
  assert.match(optionalRuntimeProbe, /api\/ocr\/glm\/ollama\/status/);
  assert.match(hypervisorProbe, /api\/system\/hypervisor/);
  assert.match(hypervisorProbe, /BIOS要確認/);
  assert.match(hypervisorProbe, /Windows機能要確認/);
  assert.match(viewModel, /RhodesHypervisorProbe\.ProbeAsync/);
  assert.match(viewModel, /_hypervisorStatus\.State/);
  assert.match(runtimeProbe, /Visual C\+\+ 2015-2022 Redistributable x64/);
  assert.match(runtimeProbe, /vcruntime140_1\.dll/);
  assert.match(runtimeProbe, /BuildStatus/);
  assert.match(runtimeProbe, /NativeRuntimeDirectory/);
});

test("MAA resource generator converts RHODES recognition definitions into pipeline nodes", async () => {
  const generator = await fs.readFile("tools/generate-maa-resource.mjs", "utf8");
  const generated = JSON.parse(
    await fs.readFile("apps/rhodes-suki/resource/base/pipeline/rhodes-generated.json", "utf8"),
  );

  assert.match(generator, /data.*recognition.*maa-tasks\.json/s);
  assert.match(generator, /scan-profiles\.json/);
  assert.equal(generated.RhodesOcrRegion_run_hope_current.recognition, "OCR");
  assert.deepEqual(generated.RhodesOcrRegion_run_hope_current.roi, [941, 17, 32, 35]);
  assert.equal(generated.RhodesTemplate_runStatusFull_run_ingot.recognition, "TemplateMatch");
  assert.equal(generated.RhodesTemplate_runStatusFull_run_ingot.template, "run/IngotIcon.png");
});

test("MAA resource generator output is checked into the Suki shell", () => {
  execFileSync(process.execPath, ["tools/generate-maa-resource.mjs", "--check"], {
    cwd: process.cwd(),
    stdio: "pipe",
  });
});

test("Suki shell exposes manual MAA ADB and probe controls", async () => {
  const xaml = await fs.readFile("apps/rhodes-suki/Views/MainWindow.axaml", "utf8");

  assert.match(xaml, /MAA ADB接続/);
  assert.match(xaml, /AdbPath/);
  assert.match(xaml, /AdbSerial/);
  assert.match(xaml, /AdbPresets/);
  assert.match(xaml, /AdbDevices/);
  assert.match(xaml, /ApplyAdbPresetCommand/);
  assert.match(xaml, /RefreshAdbDevicesCommand/);
  assert.match(xaml, /ApplyAdbDeviceCommand/);
  assert.match(xaml, /RefreshOptionalRuntimesCommand/);
  assert.match(xaml, /SaveSettingsCommand/);
  assert.match(xaml, /ConnectCommand/);
  assert.match(xaml, /CaptureCommand/);
  assert.match(xaml, /Image Source="\{Binding LastCaptureImage\}"/);
  assert.match(xaml, /RunResourceTaskCommand/);
  assert.match(xaml, /RunSelectedProfileRecognitionCommand/);
  assert.match(xaml, /RunSelectedProfileRecognitionAndApplyCommand/);
  assert.match(xaml, /RunSelectedProfileAdbScanCommand/);
  assert.match(xaml, /ADB API/);
  assert.match(xaml, /SyncRunStateFromApiCommand/);
  assert.match(xaml, /API状態同期/);
  assert.match(xaml, /OpenRecognitionProfileCommand/);
  assert.match(xaml, /CommandParameter="\{Binding ProfileId\}"/);
  assert.match(xaml, /CommandParameter="runStatusFull"/);
  assert.match(xaml, /CommandParameter="operatorsFull"/);
  assert.match(xaml, /CommandParameter="relicsFull"/);
  assert.match(xaml, /CommandParameter="is5ThoughtFull"/);
  assert.match(xaml, /RunAllResourceTasksCommand/);
  assert.match(xaml, /ExportResourceTaskResultsCommand/);
  assert.match(xaml, /RefreshRecognitionScanHistoryCommand/);
  assert.match(xaml, /LoadRecognitionScanHistoryCommand/);
  assert.match(xaml, /RecognitionScanHistory/);
  assert.match(xaml, /RecognitionScanLogRows/);
  assert.match(xaml, /OcrDetailRows/);
  assert.match(xaml, /RoiPreviewRows/);
  assert.match(xaml, /SelectedRoiPreviewRows/);
  assert.match(xaml, /DisplayTitle/);
  assert.match(xaml, /EditKindLabel/);
  assert.match(xaml, /ProjectedRoiJson/);
  assert.match(xaml, /SelectedRoiEditDraft\.StatusLabel/);
  assert.match(xaml, /SelectedRoiEditDraft\.RoiJson/);
  assert.match(xaml, /SelectedRoiEditDraft\.Detail/);
  assert.match(xaml, /x:Name="RoiCanvas"/);
  assert.match(xaml, /PointerPressed="RoiOverlayPointerPressed"/);
  assert.match(xaml, /PointerMoved="RoiOverlayPointerMoved"/);
  assert.match(xaml, /PointerReleased="RoiOverlayPointerReleased"/);
  assert.match(xaml, /TopLeftHandleX/);
  assert.match(xaml, /TopLeftHandleY/);
  assert.match(xaml, /LeftHandleX/);
  assert.match(xaml, /TopHandleX/);
  assert.match(xaml, /RightHandleX/);
  assert.match(xaml, /BottomHandleX/);
  assert.match(xaml, /ResizeHandleX/);
  assert.match(xaml, /ResizeHandleY/);
  assert.match(xaml, /Tag="topLeft"/);
  assert.match(xaml, /Tag="left"/);
  assert.match(xaml, /Tag="top"/);
  assert.match(xaml, /Tag="right"/);
  assert.match(xaml, /Tag="bottom"/);
  assert.match(xaml, /Tag="bottomRight"/);
  assert.match(xaml, /PointerPressed="RoiResizePointerPressed"/);
  assert.match(xaml, /PointerMoved="RoiResizePointerMoved"/);
  assert.match(xaml, /PointerReleased="RoiResizePointerReleased"/);
  assert.match(xaml, /ExportSelectedRoiDraftCommand/);
  assert.match(xaml, /RoiSnapStepLabel/);
  assert.match(xaml, /SetRoiSnapStepCommand/);
  assert.match(xaml, /ResetSelectedRoiDraftCommand/);
  assert.match(xaml, /元に戻す/);
  assert.match(xaml, /CommandParameter="4"/);
  assert.match(xaml, /CommandParameter="8"/);
  assert.match(xaml, /AdjustSelectedRoiDraftCommand/);
  assert.match(xaml, /CommandParameter="left"/);
  assert.match(xaml, /CommandParameter="wider"/);
  assert.match(xaml, /PreviewSelectedRoiDraftApplyCommand/);
  assert.match(xaml, /ApplySelectedRoiDraftCommand/);
  assert.match(xaml, /PreviewVisibleRoiDraftsApplyCommand/);
  assert.match(xaml, /ApplyVisibleRoiDraftsCommand/);
  assert.match(xaml, /IncludeAllRoiBatchDraftsCommand/);
  assert.match(xaml, /ExcludeAllRoiBatchDraftsCommand/);
  assert.match(xaml, /ExportRoiAdjustmentSessionCommand/);
  assert.match(xaml, /RoiAdjustmentSessions/);
  assert.match(xaml, /RoiSessionRestoreNotice/);
  assert.match(xaml, /RefreshRoiAdjustmentSessionsCommand/);
  assert.match(xaml, /LoadRoiAdjustmentSessionCommand/);
  assert.match(xaml, /RegenerateMaaResourceCommand/);
  assert.match(xaml, /MaaResourceGenerationResult\.Message/);
  assert.match(xaml, /RoiDraftApplyResult\.Message/);
  assert.match(xaml, /RoiDraftApplyResult\.TargetSummary/);
  assert.match(xaml, /RoiDraftApplyResult\.DiffSummary/);
  assert.match(xaml, /RoiDraftApplyResult\.BackupSummary/);
  assert.match(xaml, /RoiBatchApplyResult\.Summary/);
  assert.match(xaml, /RoiBatchApplyResult\.BackupSummary/);
  assert.match(xaml, /RoiBatchDrafts/);
  assert.match(xaml, /IsIncluded, Mode=TwoWay/);
  assert.match(xaml, /StateLabel/);
  assert.match(xaml, /StateDetail/);
  assert.match(xaml, /RoiBatchApplyResult\.Results/);
  assert.match(xaml, /TargetSummary/);
  assert.match(xaml, /DiffSummary/);
  assert.match(xaml, /SelectedItem="\{Binding SelectedRoiPreviewRow, Mode=TwoWay\}"/);
  assert.match(xaml, /SelectedItem="\{Binding SelectedOcrDetailRow, Mode=TwoWay\}"/);
  assert.match(xaml, /SelectedItem="\{Binding SelectedRecognitionScanLogRow, Mode=TwoWay\}"/);
  assert.match(xaml, /SelectedItem="\{Binding SelectedResourceTaskResult, Mode=TwoWay\}"/);
  assert.match(xaml, /BorderBrush="#FFD447"/);
  assert.match(xaml, /ShowRoiOverlay/);
  assert.match(xaml, /CapturePixelSizeLabel/);
  assert.match(xaml, /RoiProjectionLabel/);
  assert.match(xaml, /Content="ROI"/);
  assert.match(xaml, /Canvas Width="1280" Height="720"/);
  assert.match(xaml, /Canvas\.Left="\{Binding X\}"/);
  assert.match(xaml, /Canvas\.Top="\{Binding Y\}"/);
  assert.match(xaml, /スキャン履歴/);
  assert.match(xaml, /SelectedResourceProfile/);
  assert.match(xaml, /ResourceProfiles/);
  assert.match(xaml, /ProfileSummary/);
  assert.match(xaml, /SourceSummary/);
  assert.match(xaml, /ConvertResourceTaskResultsCommand/);
  assert.match(xaml, /CandidateResults/);
  assert.match(xaml, /LastCandidateApplySummary/);
  assert.match(xaml, /ResourceTaskDiagnostics/);
  assert.match(xaml, /RhodesApiUrl/);
  assert.match(xaml, /RunProbeCommand/);
  assert.match(xaml, /ResourceTaskResults/);
  assert.match(xaml, /ProbeResults/);
  assert.match(xaml, /RecognitionDetailJson/);
  assert.match(xaml, /Campaigns/);
  assert.match(xaml, /SelectedCampaign/);
  assert.match(xaml, /WORKSPACE/);
  assert.match(xaml, /WorkspaceNav/);
  assert.match(xaml, /SetWorkspaceCommand/);
  assert.match(xaml, /CampaignHeaderTitle/);
  assert.match(xaml, /CampaignHeaderDetail/);
  assert.match(xaml, /HeaderStatusChips/);
  assert.match(xaml, /RunFieldPreviews/);
  assert.match(xaml, /CampaignPreviews/);
  assert.match(xaml, /SpecialValuePreviews/);
  assert.match(xaml, /IS固有値/);
  assert.match(xaml, /IS切替/);
  assert.match(xaml, /選択カタログ/);
  assert.match(xaml, /オペレーター/);
  assert.match(xaml, /秘宝/);
  assert.match(xaml, /認識ワークフロー/);
  assert.match(xaml, /出力 \/ OBS/);
  assert.match(xaml, /OutputParts/);
  assert.match(xaml, /OutputSeparateWindow/);
  assert.match(xaml, /OutputTournamentMode/);
  assert.match(xaml, /OutputTransparentBackground/);
  assert.match(xaml, /OutputScrollSpeed/);
  assert.match(xaml, /ScrollEnabled/);
  assert.match(xaml, /HideExcluded/);
  assert.match(xaml, /BindingPath/);
  assert.match(xaml, /ランタイム/);
  assert.match(xaml, /RuntimeCapabilities/);
  assert.match(xaml, /InstallLabel/);
  assert.match(xaml, /状態確認/);
  assert.match(xaml, /インスペクタ/);
  assert.match(xaml, /InspectorRows/);
  assert.match(xaml, /FilteredOperatorRows/);
  assert.match(xaml, /FilteredRelicRows/);
  assert.match(xaml, /RhodesBitmapPathConverter/);
  assert.match(xaml, /ImagePath, Converter=\{StaticResource BitmapPathConverter\}/);
  assert.match(xaml, /PlainComboItemTemplate/);
  assert.match(xaml, /SelectionBoxItemTemplate="\{StaticResource PlainComboItemTemplate\}"/);
  assert.match(xaml, /SelectionBoxItemTemplate="\{StaticResource CampaignComboItemTemplate\}"/);
  assert.match(xaml, /SelectionBoxItemTemplate="\{StaticResource AdbPresetSelectionTemplate\}"/);
  assert.match(xaml, /Selector="ComboBoxItem"/);
  assert.match(xaml, /Text="\{Binding Name\}"/);
  assert.match(xaml, /Text="\{Binding Heading\}"/);
  assert.match(xaml, /Text="\{Binding Detail\}"/);
  assert.match(xaml, /OperatorSearch/);
  assert.match(xaml, /RelicSearch/);
  assert.match(xaml, /OperatorSearch, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged/);
  assert.match(xaml, /RelicSearch, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged/);
  assert.match(xaml, /PaneColumnOptions/);
  assert.match(xaml, /OperatorPaneColumns/);
  assert.match(xaml, /RelicPaneColumns/);
  assert.match(xaml, /Selector="ListBox\.choicePane ListBoxItem"/);
  assert.match(xaml, /HorizontalContentAlignment" Value="Stretch"/);
  assert.match(xaml, /Content="\{TemplateBinding Content\}"/);
  assert.match(xaml, /ContentTemplate="\{TemplateBinding ContentTemplate\}"/);
  assert.match(xaml, /ListBox Grid\.Row="2" Classes="choicePane" ItemsSource="\{Binding FilteredOperatorRows\}"/);
  assert.match(xaml, /ListBox Grid\.Row="2" Classes="choicePane" ItemsSource="\{Binding FilteredRelicRows\}"/);
  assert.match(xaml, /UniformGrid Columns="\{Binding Columns\}"/);
  assert.match(xaml, /UniformGrid Columns="\{Binding Columns\}" HorizontalAlignment="Stretch"/);
  assert.match(xaml, /RelativeSource=\{RelativeSource AncestorType=Window\}/);
  assert.match(xaml, /Selector="Button\.choiceCard"/);
  assert.match(xaml, /Classes="choiceCard"/);
  assert.match(xaml, /Background="\{TemplateBinding Background\}"/);
  assert.match(xaml, /MinHeight="\{TemplateBinding MinHeight\}"/);
  assert.match(xaml, /<Button Classes="choiceCard" Command="\{Binding DataContext\.ToggleChoiceSelectedCommand, RelativeSource=\{RelativeSource AncestorType=Window\}\}"/);
  assert.doesNotMatch(xaml, /<Button Classes="choiceCard"[^>]*>\s*<Border CornerRadius="7" Padding="9"/);
  assert.doesNotMatch(xaml, /SelectionButtonLabel/);
  assert.doesNotMatch(xaml, /ExclusionButtonLabel/);
  assert.doesNotMatch(xaml, /ToggleChoiceExcludedCommand/);
  assert.doesNotMatch(xaml, /タグで検索/);
  assert.match(xaml, /OperatorShowSelectedFirst/);
  assert.match(xaml, /RelicShowSelectedFirst/);
  assert.match(xaml, /ToggleChoiceSelectedCommand/);
});

test("MAAFramework roadmap records 1280x720 as a 16:9 base coordinate system", async () => {
  const roadmap = await fs.readFile("docs/maaframework-family-roadmap.md", "utf8");
  const notice = await fs.readFile("THIRD_PARTY_NOTICES.md", "utf8");

  assert.match(roadmap, /1280x720/);
  assert.match(roadmap, /16:9/);
  assert.match(roadmap, /maa-resource-scan-runner\.js/);
  assert.match(roadmap, /MFAToolsPlus/);
  assert.match(notice, /SweetSmellFox\/MFAToolsPlus/);
});

test("Suki design docs require operational operator and relic UI", async () => {
  const principles = await fs.readFile("docs/suki-workbench-design-principles.md", "utf8");
  const stitch = await fs.readFile("docs/stitch-suki-workbench-brief.md", "utf8");

  assert.match(principles, /Operational selection first/);
  assert.match(principles, /Stable workspaces over tab sprawl/);
  assert.match(principles, /operator and relic catalogs/);
  assert.match(principles, /Output part enabled/);
  assert.match(principles, /Runtime required vs optional capabilities/);
  assert.match(principles, /RhodesRunCatalog/);
  assert.match(stitch, /Run workspace/);
  assert.match(stitch, /Choices workspace/);
  assert.match(stitch, /Output workspace/);
  assert.match(stitch, /Runtime workspace/);
  assert.match(stitch, /IS campaign selected and switchable/);
});
