import test from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import fs from "node:fs/promises";

test("Suki shell references SukiUI and Maa.Framework as the replacement desktop stack", async () => {
  const csproj = await fs.readFile("apps/rhodes-suki/RhodesSuki.csproj", "utf8");
  const packageJson = await fs.readFile("package.json", "utf8");

  assert.match(csproj, /PackageReference Include="SukiUI" Version="7\.0\.1"/);
  assert.match(csproj, /PackageReference Include="Maa\.Framework" Version="5\.8\.0"/);
  assert.match(csproj, /resource\\base\\pipeline\\rhodes\.json/);
  assert.match(csproj, /resource\\base\\pipeline\\rhodes-generated\.json/);
  assert.match(csproj, /interface\.json/);
  assert.match(csproj, /assets\\recognition\\templates\\run\\\*\.png/);
  assert.match(csproj, /assets\\operators\\\*\*\\\*\.png/);
  assert.match(csproj, /assets\\relics\\\*\*\\\*\.png/);
  assert.match(csproj, /data\\campaigns\.json/);
  assert.match(csproj, /data\\operators\.json/);
  assert.match(csproj, /data\\relics\.json/);
  assert.match(csproj, /data\\current-state\.json/);
  assert.match(csproj, /data\\selectable-effects\.json/);
  assert.match(packageJson, /"maa:resource:generate": "node tools\/generate-maa-resource\.mjs"/);
  assert.match(packageJson, /"maa:resource:check": "node tools\/generate-maa-resource\.mjs --check"/);
  assert.match(packageJson, /"suki:test": "dotnet run --project tests\/rhodes-suki\/RhodesSuki\.ServiceTests\.csproj"/);
  assert.match(packageJson, /suki:publish:portable.*--self-contained true/);
});

test("Suki service tests cover MAA Resource detail conversion behavior", async () => {
  const testProject = await fs.readFile("tests/rhodes-suki/RhodesSuki.ServiceTests.csproj", "utf8");
  const program = await fs.readFile("tests/rhodes-suki/Program.cs", "utf8");

  assert.match(testProject, /ProjectReference Include="..\\..\\apps\\rhodes-suki\\RhodesSuki\.csproj"/);
  assert.match(program, /RhodesMaaResultPreview\.FromTaskResults/);
  assert.match(program, /best_result/);
  assert.match(program, /filtered_results/);
  assert.match(program, /TemplateMatch/);
  assert.match(program, /HitFallback/);
  assert.match(program, /RhodesAdbPresetCatalog\.DefaultPresets/);
  assert.match(program, /RhodesAdbDeviceProbe\.ParseDevices/);
  assert.match(program, /RhodesSukiSettingsStore\.Save/);
  assert.match(program, /google-play-games-dev/);
});

test("Suki shell keeps MAA session and probe code in thin RHODES-owned services", async () => {
  const session = await fs.readFile("apps/rhodes-suki/Services/RhodesMaaSession.cs", "utf8");
  const optionalRuntimeProbe = await fs.readFile("apps/rhodes-suki/Services/RhodesOptionalRuntimeProbe.cs", "utf8");
  const hypervisorProbe = await fs.readFile("apps/rhodes-suki/Services/RhodesHypervisorProbe.cs", "utf8");
  const runtimeProbe = await fs.readFile("apps/rhodes-suki/Services/MaaFrameworkRuntimeProbe.cs", "utf8");
  const probe = await fs.readFile("apps/rhodes-suki/Services/RhodesRecognitionProbe.cs", "utf8");
  const catalog = await fs.readFile("apps/rhodes-suki/Services/RhodesMaaResourceCatalog.cs", "utf8");
  const adbPresets = await fs.readFile("apps/rhodes-suki/Services/RhodesAdbPresetCatalog.cs", "utf8");
  const adbDeviceProbe = await fs.readFile("apps/rhodes-suki/Services/RhodesAdbDeviceProbe.cs", "utf8");
  const settingsStore = await fs.readFile("apps/rhodes-suki/Services/RhodesSukiSettingsStore.cs", "utf8");
  const diagnostics = await fs.readFile("apps/rhodes-suki/Services/RhodesMaaTaskDiagnostics.cs", "utf8");
  const resultPreview = await fs.readFile("apps/rhodes-suki/Services/RhodesMaaResultPreview.cs", "utf8");
  const runCatalog = await fs.readFile("apps/rhodes-suki/Services/RhodesRunCatalog.cs", "utf8");
  const bitmapPathConverter = await fs.readFile("apps/rhodes-suki/Services/RhodesBitmapPathConverter.cs", "utf8");
  const choiceFilter = await fs.readFile("apps/rhodes-suki/Services/RhodesChoiceFilter.cs", "utf8");
  const choiceRows = await fs.readFile("apps/rhodes-suki/Services/RhodesChoiceRows.cs", "utf8");
  const operatorTaxonomy = await fs.readFile("apps/rhodes-suki/Services/RhodesOperatorTaxonomy.cs", "utf8");
  const runStateStore = await fs.readFile("apps/rhodes-suki/Services/RhodesRunStateStore.cs", "utf8");
  const candidateApplier = await fs.readFile("apps/rhodes-suki/Services/RhodesRecognitionCandidateApplier.cs", "utf8");
  const candidateApiClient = await fs.readFile("apps/rhodes-suki/Services/RhodesMaaCandidateApiClient.cs", "utf8");
  const scanApiClient = await fs.readFile("apps/rhodes-suki/Services/RhodesRecognitionScanApiClient.cs", "utf8");
  const models = await fs.readFile("apps/rhodes-suki/Models/MaaSessionModels.cs", "utf8");
  const runModels = await fs.readFile("apps/rhodes-suki/Models/RunCatalogModels.cs", "utf8");
  const viewModel = await fs.readFile("apps/rhodes-suki/ViewModels/MainWindowViewModel.cs", "utf8");
  const mainWindowCodeBehind = await fs.readFile("apps/rhodes-suki/Views/MainWindow.axaml.cs", "utf8");
  const resource = await fs.readFile("apps/rhodes-suki/resource/base/pipeline/rhodes.json", "utf8");
  const generatedResource = await fs.readFile("apps/rhodes-suki/resource/base/pipeline/rhodes-generated.json", "utf8");
  const projectInterface = await fs.readFile("apps/rhodes-suki/interface.json", "utf8");

  assert.match(session, /new MaaAdbController/);
  assert.match(session, /new MaaTasker/);
  assert.match(session, /GetCachedImage/);
  assert.match(session, /AppendTask/);
  assert.match(session, /GetRecognitionDetail/);
  assert.match(session, /RecognitionDetailJson/);
  assert.match(probe, /AppendRecognition/);
  assert.match(probe, /TemplateMatch/);
  assert.match(probe, /RecognitionDetailJson/);
  assert.match(catalog, /rhodes-generated\.json/);
  assert.match(catalog, /JsonDocument\.Parse/);
  assert.match(catalog, /GeneratedTasks/);
  assert.match(catalog, /ProfileGroups/);
  assert.match(catalog, /profileIds/);
  assert.match(adbPresets, /google-play-games-dev/);
  assert.match(adbPresets, /127\.0\.0\.1:6520/);
  assert.match(adbPresets, /127\.0\.0\.1:16384/);
  assert.match(adbDeviceProbe, /devices/);
  assert.match(adbDeviceProbe, /ParseDevices/);
  assert.match(settingsStore, /suki-settings\.json/);
  assert.match(settingsStore, /RhodesSukiSettings/);
  assert.match(diagnostics, /RhodesMaaTaskDiagnostics/);
  assert.match(diagnostics, /RhodesMaaResultPreview\.FromTaskResults/);
  assert.match(resultPreview, /FromTaskResults/);
  assert.match(resultPreview, /best_result/);
  assert.match(resultPreview, /filtered_results/);
  assert.match(resultPreview, /MaaCandidatePreview/);
  assert.match(runCatalog, /campaigns\.json/);
  assert.match(runCatalog, /operators\.json/);
  assert.match(runCatalog, /relics\.json/);
  assert.match(runCatalog, /current-state\.json/);
  assert.match(runCatalog, /selectable-effects\.json/);
  assert.match(runCatalog, /ResolveStatePath/);
  assert.match(runCatalog, /IsProjectRootStatePath/);
  assert.match(runCatalog, /ResolveLocalPath/);
  assert.match(runCatalog, /SukiRunStateSnapshot/);
  assert.match(bitmapPathConverter, /IValueConverter/);
  assert.match(bitmapPathConverter, /new Bitmap\(path\)/);
  assert.match(choiceFilter, /ShowSelectedFirst/);
  assert.match(choiceFilter, /HideExcluded/);
  assert.match(choiceFilter, /SelectedOnly/);
  assert.match(choiceFilter, /RequiresFullRefreshAfterSelectionMutation/);
  assert.match(choiceFilter, /RequiresFullRefreshAfterExclusionMutation/);
  assert.match(choiceFilter, /OperatorClass/);
  assert.match(choiceFilter, /OperatorBranch/);
  assert.match(choiceFilter, /Category/);
  assert.match(choiceFilter, /Rarity/);
  assert.match(choiceRows, /Math\.Clamp\(columns, 1, 4\)/);
  assert.match(choiceRows, /new SukiChoiceRow/);
  assert.match(operatorTaxonomy, /SortClasses/);
  assert.match(operatorTaxonomy, /SortBranches/);
  assert.match(operatorTaxonomy, /"先鋒"/);
  assert.match(operatorTaxonomy, /"執行者"/);
  assert.match(runStateStore, /SaveChoicesAsync/);
  assert.match(runStateStore, /SaveRunContextAsync/);
  assert.match(runStateStore, /SaveCandidatesAsync/);
  assert.match(runStateStore, /SemaphoreSlim/);
  assert.match(runStateStore, /operatorExcludedIds/);
  assert.match(runStateStore, /operatorGridColumns/);
  assert.match(candidateApplier, /ApplyRunStatus/);
  assert.match(candidateApplier, /ApplyStringSetCandidate/);
  assert.match(candidateApplier, /commandLevel/);
  assert.match(candidateApplier, /squadId/);
  assert.match(candidateApplier, /idea/);
  assert.match(candidateApplier, /operator/);
  assert.match(candidateApplier, /relic/);
  assert.match(models, /MaaTaskDetailSnapshot/);
  assert.match(models, /MaaResourceProfilePreview/);
  assert.match(models, /SukiOptionalRuntimeStatus/);
  assert.match(models, /MaaCandidatePreview/);
  assert.match(models, /SukiCandidateApplySummary/);
  assert.match(models, /ProfileIds/);
  assert.match(models, /SourceSummary/);
  assert.match(models, /RecognitionDetailJson/);
  assert.match(runModels, /SukiCampaignPreview/);
  assert.match(runModels, /SukiSpecialFieldState/);
  assert.match(runModels, /SukiChoiceItem/);
  assert.match(runModels, /SukiChoiceRow/);
  assert.match(runModels, /ImagePath/);
  assert.match(runModels, /SelectionButtonLabel/);
  assert.match(runModels, /ExclusionButtonLabel/);
  assert.match(viewModel, /ConnectCommand/);
  assert.match(viewModel, /CaptureCommand/);
  assert.match(viewModel, /Bitmap/);
  assert.match(viewModel, /LastCaptureImage/);
  assert.match(viewModel, /AdbPresets/);
  assert.match(viewModel, /AdbDevices/);
  assert.match(viewModel, /ApplyAdbPresetCommand/);
  assert.match(viewModel, /RefreshAdbDevicesCommand/);
  assert.match(viewModel, /ApplyAdbDeviceCommand/);
  assert.match(viewModel, /RefreshOptionalRuntimesCommand/);
  assert.match(viewModel, /RhodesOptionalRuntimeProbe\.ProbeAsync/);
  assert.match(viewModel, /_maaFrameworkStatus\.State/);
  assert.match(viewModel, /_maaFrameworkStatus\.Detail/);
  assert.match(viewModel, /SaveSettingsCommand/);
  assert.match(viewModel, /LoadSettings/);
  assert.match(viewModel, /ResourceTaskDiagnostics/);
  assert.match(viewModel, /MaaOcrStatusState/);
  assert.match(viewModel, /Resource化済み/);
  assert.doesNotMatch(viewModel, /"MAA-OCR",\s*"移行対象"/);
  assert.match(viewModel, /RunAllProbesCommand/);
  assert.match(viewModel, /RunSelectedProfileRecognitionCommand/);
  assert.match(viewModel, /RunSelectedProfileRecognitionAndApplyCommand/);
  assert.match(viewModel, /OpenRecognitionProfileCommand/);
  assert.match(viewModel, /RunAllResourceTasksCommand/);
  assert.match(viewModel, /ExportResourceTaskResultsCommand/);
  assert.match(viewModel, /SelectedResourceProfile/);
  assert.match(viewModel, /RefreshResourceTasks/);
  assert.match(viewModel, /ConvertResourceTaskResultsCommand/);
  assert.match(viewModel, /ApplyCandidateResultsCommand/);
  assert.match(viewModel, /LastCandidateApplySummary/);
  assert.match(viewModel, /LastResourceTaskResultsPath/);
  assert.match(viewModel, /RefreshChoicesFromRunState/);
  assert.match(viewModel, /RhodesMaaCandidateApiClient\.ConvertAsync/);
  assert.match(viewModel, /RhodesMaaLocalCandidateConverter\.FromTaskResults/);
  assert.match(candidateApiClient, /api\/recognition\/maa-resource/);
  assert.match(candidateApiClient, /ExtractCandidatePreviews/);
  assert.match(scanApiClient, /api\/recognition\/scan/);
  assert.match(scanApiClient, /ExtractResult/);
  assert.match(scanApiClient, /RhodesMaaCandidateApiClient\.ExtractCandidatePreviews/);
  assert.match(viewModel, /CandidateApiProfileId/);
  assert.match(viewModel, /RunSelectedProfileAdbScanCommand/);
  assert.match(viewModel, /RhodesRecognitionScanApiClient\.RunAsync/);
  assert.doesNotMatch(viewModel, /SelectedResourceProfile\?\.Id == "all" \? "runStatusFull"/);
  assert.match(viewModel, /RhodesMaaResultPreview\.FromTaskResults/);
  assert.match(viewModel, /CandidateResults/);
  assert.match(viewModel, /RunResourceTaskCommand/);
  assert.match(viewModel, /maa-resource-results/);
  assert.match(viewModel, /JsonSerializer\.Serialize/);
  assert.match(viewModel, /Campaigns/);
  assert.match(viewModel, /SelectedCampaign/);
  assert.match(viewModel, /構想/);
  assert.doesNotMatch(viewModel, /想念/);
  assert.match(viewModel, /FilteredOperators/);
  assert.match(viewModel, /FilteredRelics/);
  assert.match(viewModel, /FilteredOperatorRows/);
  assert.match(viewModel, /FilteredRelicRows/);
  assert.match(viewModel, /ToggleChoiceSelectedCommand/);
  assert.match(viewModel, /ToggleChoiceExcludedCommand/);
  assert.match(viewModel, /PaneColumnOptions/);
  assert.match(viewModel, /OperatorPaneColumns/);
  assert.match(viewModel, /RelicPaneColumns/);
  assert.match(viewModel, /ClampPaneColumns/);
  assert.match(viewModel, /RefreshChoiceAfterSelectionMutation/);
  assert.match(viewModel, /RefreshChoiceAfterExclusionMutation/);
  assert.match(viewModel, /PersistChoiceStateInBackground\(\);/);
  assert.match(viewModel, /RefreshOperatorSummaries/);
  assert.match(viewModel, /RefreshRelicSummaries/);
  assert.match(viewModel, /RefreshOperatorRows/);
  assert.match(viewModel, /RefreshRelicRows/);
  assert.match(viewModel, /RhodesOperatorTaxonomy\.SortClasses/);
  assert.match(viewModel, /RhodesOperatorTaxonomy\.SortBranches/);
  assert.match(viewModel, /RhodesRunStateStore\.SaveChoicesAsync/);
  assert.match(viewModel, /RhodesRunStateStore\.SaveCandidatesAsync/);
  assert.match(viewModel, /SetCurrentCampaignCommand/);
  assert.match(viewModel, /SequenceEqual\(items\)/);
  assert.match(mainWindowCodeBehind, /CloseOpenComboBoxesOnOutsidePress/);
  assert.match(mainWindowCodeBehind, /IsDropDownOpen = false/);
  assert.match(resource, /RhodesRunStatusTopBarOcr/);
  assert.match(resource, /RhodesOperatorCodenameFlag/);
  assert.match(resource, /OperatorCardCodeNameFlag\.png/);
  assert.match(generatedResource, /RhodesOcrRegion_run_hope_current/);
  assert.match(generatedResource, /RhodesTemplate_runStatusFull_run_ingot/);
  assert.match(generatedResource, /scan-profiles\.templateOcrRegions/);
  assert.match(projectInterface, /"interface_version": 2/);
  assert.match(projectInterface, /"entry": "RhodesOperatorNameOcr"/);
  assert.match(resource, /RhodesProbe/);
  assert.match(optionalRuntimeProbe, /api\/ocr\/glm\/status/);
  assert.match(optionalRuntimeProbe, /api\/ocr\/glm\/ollama\/status/);
  assert.match(hypervisorProbe, /api\/system\/hypervisor/);
  assert.match(hypervisorProbe, /BIOS要確認/);
  assert.match(hypervisorProbe, /Windows機能要確認/);
  assert.match(viewModel, /RhodesHypervisorProbe\.ProbeAsync/);
  assert.match(viewModel, /_hypervisorStatus\.State/);
  assert.match(runtimeProbe, /Visual C\+\+ 2015-2022 Redistributable x64/);
  assert.match(runtimeProbe, /vcruntime140_1\.dll/);
  assert.match(runtimeProbe, /BuildStatus/);
  assert.match(runtimeProbe, /NativeRuntimeDirectory/);
});

test("MAA resource generator converts RHODES recognition definitions into pipeline nodes", async () => {
  const generator = await fs.readFile("tools/generate-maa-resource.mjs", "utf8");
  const generated = JSON.parse(
    await fs.readFile("apps/rhodes-suki/resource/base/pipeline/rhodes-generated.json", "utf8"),
  );

  assert.match(generator, /data.*recognition.*maa-tasks\.json/s);
  assert.match(generator, /scan-profiles\.json/);
  assert.equal(generated.RhodesOcrRegion_run_hope_current.recognition, "OCR");
  assert.deepEqual(generated.RhodesOcrRegion_run_hope_current.roi, [941, 17, 32, 35]);
  assert.equal(generated.RhodesTemplate_runStatusFull_run_ingot.recognition, "TemplateMatch");
  assert.equal(generated.RhodesTemplate_runStatusFull_run_ingot.template, "run/IngotIcon.png");
});

test("MAA resource generator output is checked into the Suki shell", () => {
  execFileSync(process.execPath, ["tools/generate-maa-resource.mjs", "--check"], {
    cwd: process.cwd(),
    stdio: "pipe",
  });
});

test("Suki shell exposes manual MAA ADB and probe controls", async () => {
  const xaml = await fs.readFile("apps/rhodes-suki/Views/MainWindow.axaml", "utf8");

  assert.match(xaml, /MAA ADB接続/);
  assert.match(xaml, /AdbPath/);
  assert.match(xaml, /AdbSerial/);
  assert.match(xaml, /AdbPresets/);
  assert.match(xaml, /AdbDevices/);
  assert.match(xaml, /ApplyAdbPresetCommand/);
  assert.match(xaml, /RefreshAdbDevicesCommand/);
  assert.match(xaml, /ApplyAdbDeviceCommand/);
  assert.match(xaml, /RefreshOptionalRuntimesCommand/);
  assert.match(xaml, /SaveSettingsCommand/);
  assert.match(xaml, /ConnectCommand/);
  assert.match(xaml, /CaptureCommand/);
  assert.match(xaml, /Image Source="\{Binding LastCaptureImage\}"/);
  assert.match(xaml, /RunResourceTaskCommand/);
  assert.match(xaml, /RunSelectedProfileRecognitionCommand/);
  assert.match(xaml, /RunSelectedProfileRecognitionAndApplyCommand/);
  assert.match(xaml, /RunSelectedProfileAdbScanCommand/);
  assert.match(xaml, /ADB API/);
  assert.match(xaml, /OpenRecognitionProfileCommand/);
  assert.match(xaml, /CommandParameter="\{Binding ProfileId\}"/);
  assert.match(xaml, /CommandParameter="runStatusFull"/);
  assert.match(xaml, /CommandParameter="operatorsFull"/);
  assert.match(xaml, /CommandParameter="relicsFull"/);
  assert.match(xaml, /CommandParameter="is5ThoughtFull"/);
  assert.match(xaml, /RunAllResourceTasksCommand/);
  assert.match(xaml, /ExportResourceTaskResultsCommand/);
  assert.match(xaml, /SelectedResourceProfile/);
  assert.match(xaml, /ResourceProfiles/);
  assert.match(xaml, /ProfileSummary/);
  assert.match(xaml, /SourceSummary/);
  assert.match(xaml, /ConvertResourceTaskResultsCommand/);
  assert.match(xaml, /CandidateResults/);
  assert.match(xaml, /LastCandidateApplySummary/);
  assert.match(xaml, /ResourceTaskDiagnostics/);
  assert.match(xaml, /RhodesApiUrl/);
  assert.match(xaml, /RunProbeCommand/);
  assert.match(xaml, /ResourceTaskResults/);
  assert.match(xaml, /ProbeResults/);
  assert.match(xaml, /RecognitionDetailJson/);
  assert.match(xaml, /Campaigns/);
  assert.match(xaml, /SelectedCampaign/);
  assert.match(xaml, /WORKSPACE/);
  assert.match(xaml, /WorkspaceNav/);
  assert.match(xaml, /SetWorkspaceCommand/);
  assert.match(xaml, /CampaignHeaderTitle/);
  assert.match(xaml, /CampaignHeaderDetail/);
  assert.match(xaml, /HeaderStatusChips/);
  assert.match(xaml, /RunFieldPreviews/);
  assert.match(xaml, /CampaignPreviews/);
  assert.match(xaml, /SpecialValuePreviews/);
  assert.match(xaml, /IS固有値/);
  assert.match(xaml, /IS切替/);
  assert.match(xaml, /選択カタログ/);
  assert.match(xaml, /オペレーター/);
  assert.match(xaml, /秘宝/);
  assert.match(xaml, /認識ワークフロー/);
  assert.match(xaml, /出力 \/ OBS/);
  assert.match(xaml, /OutputParts/);
  assert.match(xaml, /OutputSeparateWindow/);
  assert.match(xaml, /OutputTournamentMode/);
  assert.match(xaml, /OutputTransparentBackground/);
  assert.match(xaml, /OutputScrollSpeed/);
  assert.match(xaml, /ScrollEnabled/);
  assert.match(xaml, /HideExcluded/);
  assert.match(xaml, /BindingPath/);
  assert.match(xaml, /ランタイム/);
  assert.match(xaml, /RuntimeCapabilities/);
  assert.match(xaml, /InstallLabel/);
  assert.match(xaml, /状態確認/);
  assert.match(xaml, /インスペクタ/);
  assert.match(xaml, /InspectorRows/);
  assert.match(xaml, /FilteredOperatorRows/);
  assert.match(xaml, /FilteredRelicRows/);
  assert.match(xaml, /RhodesBitmapPathConverter/);
  assert.match(xaml, /ImagePath, Converter=\{StaticResource BitmapPathConverter\}/);
  assert.match(xaml, /PlainComboItemTemplate/);
  assert.match(xaml, /SelectionBoxItemTemplate="\{StaticResource PlainComboItemTemplate\}"/);
  assert.match(xaml, /SelectionBoxItemTemplate="\{StaticResource CampaignComboItemTemplate\}"/);
  assert.match(xaml, /SelectionBoxItemTemplate="\{StaticResource AdbPresetSelectionTemplate\}"/);
  assert.match(xaml, /Selector="ComboBoxItem"/);
  assert.match(xaml, /Text="\{Binding Name\}"/);
  assert.match(xaml, /Text="\{Binding Heading\}"/);
  assert.match(xaml, /Text="\{Binding Detail\}"/);
  assert.match(xaml, /OperatorSearch/);
  assert.match(xaml, /RelicSearch/);
  assert.match(xaml, /OperatorSearch, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged/);
  assert.match(xaml, /RelicSearch, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged/);
  assert.match(xaml, /PaneColumnOptions/);
  assert.match(xaml, /OperatorPaneColumns/);
  assert.match(xaml, /RelicPaneColumns/);
  assert.match(xaml, /Selector="ListBox\.choicePane ListBoxItem"/);
  assert.match(xaml, /HorizontalContentAlignment" Value="Stretch"/);
  assert.match(xaml, /Content="\{TemplateBinding Content\}"/);
  assert.match(xaml, /ContentTemplate="\{TemplateBinding ContentTemplate\}"/);
  assert.match(xaml, /ListBox Grid\.Row="2" Classes="choicePane" ItemsSource="\{Binding FilteredOperatorRows\}"/);
  assert.match(xaml, /ListBox Grid\.Row="2" Classes="choicePane" ItemsSource="\{Binding FilteredRelicRows\}"/);
  assert.match(xaml, /UniformGrid Columns="\{Binding Columns\}"/);
  assert.match(xaml, /UniformGrid Columns="\{Binding Columns\}" HorizontalAlignment="Stretch"/);
  assert.match(xaml, /RelativeSource=\{RelativeSource AncestorType=Window\}/);
  assert.match(xaml, /Selector="Button\.choiceCard"/);
  assert.match(xaml, /Classes="choiceCard"/);
  assert.match(xaml, /Background="\{TemplateBinding Background\}"/);
  assert.match(xaml, /MinHeight="\{TemplateBinding MinHeight\}"/);
  assert.match(xaml, /<Button Classes="choiceCard" Command="\{Binding DataContext\.ToggleChoiceSelectedCommand, RelativeSource=\{RelativeSource AncestorType=Window\}\}"/);
  assert.doesNotMatch(xaml, /<Button Classes="choiceCard"[^>]*>\s*<Border CornerRadius="7" Padding="9"/);
  assert.doesNotMatch(xaml, /SelectionButtonLabel/);
  assert.doesNotMatch(xaml, /ExclusionButtonLabel/);
  assert.doesNotMatch(xaml, /ToggleChoiceExcludedCommand/);
  assert.doesNotMatch(xaml, /タグで検索/);
  assert.match(xaml, /OperatorShowSelectedFirst/);
  assert.match(xaml, /RelicShowSelectedFirst/);
  assert.match(xaml, /ToggleChoiceSelectedCommand/);
});

test("MAAFramework roadmap records 1280x720 as a 16:9 base coordinate system", async () => {
  const roadmap = await fs.readFile("docs/maaframework-family-roadmap.md", "utf8");
  const notice = await fs.readFile("THIRD_PARTY_NOTICES.md", "utf8");

  assert.match(roadmap, /1280x720/);
  assert.match(roadmap, /16:9/);
  assert.match(roadmap, /maa-resource-scan-runner\.js/);
  assert.match(roadmap, /MFAToolsPlus/);
  assert.match(notice, /SweetSmellFox\/MFAToolsPlus/);
});

test("Suki design docs require operational operator and relic UI", async () => {
  const principles = await fs.readFile("docs/suki-workbench-design-principles.md", "utf8");
  const stitch = await fs.readFile("docs/stitch-suki-workbench-brief.md", "utf8");

  assert.match(principles, /Operational selection first/);
  assert.match(principles, /Stable workspaces over tab sprawl/);
  assert.match(principles, /operator and relic catalogs/);
  assert.match(principles, /Output part enabled/);
  assert.match(principles, /Runtime required vs optional capabilities/);
  assert.match(principles, /RhodesRunCatalog/);
  assert.match(stitch, /Run workspace/);
  assert.match(stitch, /Choices workspace/);
  assert.match(stitch, /Output workspace/);
  assert.match(stitch, /Runtime workspace/);
  assert.match(stitch, /IS campaign selected and switchable/);
});
